### ISSUE TITLE
Anmeldung zu Veranstaltung führt zu Fehler

### ISSUE THREAD

**Issue by innosmith** [stadtluzern/decidim-ocl#160]
Die private Organisation "Echogruppe Dialog Luzern" bietet Veranstaltungen an. Sobald man sich als berechtigter User anmelden möchte, folgt die Fehlerseite gemäss Attachment. Fehlerzeitpunkt Mo 27.09.2021, 12:59.

**Comment by carlobeltrame** [comment]
Sieht so aus als wäre das ein Problem mit einem "doppeltem" Follow. Logs vom Fehler (beachte die Zeile "Gültigkeitsprüfung ist fehlgeschlagen: User ist bereits vergeben"):
```
I, [2021-09-28T09:50:17.730163 #1]  INFO -- : [bde835d7-fb04-4c45-ab08-38687ad79ba1] Started POST "/assemblies/echogruppe/f/145/meetings/151/registration" for ::ffff:178.197.238.175 at 2021-09-28 09:50:17 +0200
I, [2021-09-28T09:50:17.738983 #1]  INFO -- : [bde835d7-fb04-4c45-ab08-38687ad79ba1] Processing by Decidim::Meetings::RegistrationsController#create as HTML
I, [2021-09-28T09:50:17.739069 #1]  INFO -- : [bde835d7-fb04-4c45-ab08-38687ad79ba1]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"BGFYfmZWpg62Moz+NKVcNg5TEAks3Q5vu0Wgue6m1YMfXqhgP8DIUAk+JeLEhz9HlRI9kgAuOJu5UBVM82FQ4Q==", "assembly_slug"=>"echogruppe", "component_id"=>"145", "meeting_id"=>"151"}
I, [2021-09-28T09:50:17.786793 #1]  INFO -- : [bde835d7-fb04-4c45-ab08-38687ad79ba1] [ActiveJob] Enqueued ActionMailer::DeliveryJob (Job ID: fa56b282-0781-4dcd-88d1-81502e20d448) to DelayedJob(decidim_ocl_production_mailers) with arguments: "Decidim::Meetings::RegistrationMailer", "confirmation", "deliver_now", #<GlobalID:0x00007fa124a49210 @uri=#<URI::GID gid://decidim-ocl/Decidim::User/264>>, #<GlobalID:0x00007fa124a37d30 @uri=#<URI::GID gid://decidim-ocl/Decidim::Meetings::Meeting/151>>, #<GlobalID:0x00007fa124a36570 @uri=#<URI::GID gid://decidim-ocl/Decidim::Meetings::Registration/14>>
I, [2021-09-28T09:50:17.788398 #1]  INFO -- : [bde835d7-fb04-4c45-ab08-38687ad79ba1] [ActiveJob] Enqueued Decidim::EventPublisherJob (Job ID: 346fab5a-ce6d-4e2e-b44b-480d7840aa1a) to DelayedJob(decidim_ocl_production_events) with arguments: "decidim.events.meetings.meeting_registration_confirmed", {:event_class=>"Decidim::Meetings::MeetingRegistrationNotificationEvent", :resource=>#<GlobalID:0x00007fa1249f62b8 @uri=#<URI::GID gid://decidim-ocl/Decidim::Meetings::Meeting/151>>, :affected_users=>[#<GlobalID:0x00007fa1249f5840 @uri=#<URI::GID gid://decidim-ocl/Decidim::User/264>>], :followers=>[], :force_send=>false, :extra=>{:registration_code=>"K928VPGQ"}}
I, [2021-09-28T09:50:17.797370 #1]  INFO -- : [bde835d7-fb04-4c45-ab08-38687ad79ba1] [ActiveJob] Enqueued Decidim::EventPublisherJob (Job ID: 0e9caf20-86b5-412f-917d-a5fe7b3bd647) to DelayedJob(decidim_ocl_production_events) with arguments: "decidim.events.gamification.badge_earned", {:event_class=>"Decidim::Gamification::BadgeEarnedEvent", :resource=>#<GlobalID:0x00007fa12499f120 @uri=#<URI::GID gid://decidim-ocl/Decidim::User/264>>, :affected_users=>[#<GlobalID:0x00007fa12499e6d0 @uri=#<URI::GID gid://decidim-ocl/Decidim::User/264>>], :followers=>[], :force_send=>false, :extra=>{:badge_name=>"attended_meetings", :previous_level=>0, :current_level=>1}}
I, [2021-09-28T09:50:17.818869 #1]  INFO -- : [bde835d7-fb04-4c45-ab08-38687ad79ba1] Completed 422 Unprocessable Entity in 80ms (ActiveRecord: 44.6ms)
F, [2021-09-28T09:50:17.820114 #1] FATAL -- : [bde835d7-fb04-4c45-ab08-38687ad79ba1]   
F, [2021-09-28T09:50:17.820150 #1] FATAL -- : [bde835d7-fb04-4c45-ab08-38687ad79ba1] ActiveRecord::RecordInvalid (Gültigkeitsprüfung ist fehlgeschlagen: User ist bereits vergeben):
F, [2021-09-28T09:50:17.820172 #1] FATAL -- : [bde835d7-fb04-4c45-ab08-38687ad79ba1]   
F, [2021-09-28T09:50:17.820227 #1] FATAL -- : [bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/validations.rb:80:in `raise_validation_error'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/validations.rb:52:in `save!'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/transactions.rb:315:in `block in save!'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `synchronize'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/transactions.rb:212:in `transaction'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/transactions.rb:315:in `save!'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/suppressor.rb:48:in `save!'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/persistence.rb:53:in `create!'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/decidim-core-0.24.2/app/commands/decidim/create_follow.rb:35:in `create_follow!'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/decidim-core-0.24.2/app/commands/decidim/create_follow.rb:24:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/rectify-0.13.0/lib/rectify/command.rb:30:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/decidim-meetings-0.24.2/app/commands/decidim/meetings/join_meeting.rb:111:in `follow_meeting'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/decidim-meetings-0.24.2/app/commands/decidim/meetings/join_meeting.rb:36:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/rectify-0.13.0/lib/rectify/command.rb:30:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/decidim-meetings-0.24.2/app/controllers/decidim/meetings/registrations_controller.rb:37:in `create'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/abstract_controller/base.rb:194:in `process_action'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_controller/metal/rendering.rb:30:in `process_action'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/decidim-core-0.24.2/app/controllers/concerns/decidim/use_organization_time_zone.rb:21:in `use_organization_time_zone'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/i18n-1.8.10/lib/i18n.rb:314:in `with_locale'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/decidim-core-0.24.2/app/controllers/concerns/decidim/locale_switcher.rb:24:in `switch_locale'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:136:in `run_callbacks'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/abstract_controller/callbacks.rb:41:in `process_action'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_controller/metal/rescue.rb:22:in `process_action'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:168:in `block in instrument'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:168:in `instrument'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activerecord-5.2.6/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/abstract_controller/base.rb:134:in `process'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionview-5.2.6/lib/action_view/rendering.rb:32:in `process'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_controller/metal.rb:191:in `dispatch'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_controller/metal.rb:252:in `dispatch'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/routing/route_set.rb:34:in `serve'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/journey/router.rb:52:in `block in serve'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/journey/router.rb:35:in `each'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/journey/router.rb:35:in `serve'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/routing/route_set.rb:840:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/engine.rb:524:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/railtie.rb:190:in `public_send'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/railtie.rb:190:in `method_missing'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/routing/mapper.rb:48:in `serve'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/journey/router.rb:52:in `block in serve'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/journey/router.rb:35:in `each'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/journey/router.rb:35:in `serve'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/routing/route_set.rb:840:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/engine.rb:524:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/railtie.rb:190:in `public_send'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/railtie.rb:190:in `method_missing'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/routing/mapper.rb:48:in `serve'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/journey/router.rb:52:in `block in serve'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/journey/router.rb:35:in `each'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/journey/router.rb:35:in `serve'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/routing/route_set.rb:840:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/engine.rb:524:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/railtie.rb:190:in `public_send'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/railtie.rb:190:in `method_missing'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/routing/mapper.rb:48:in `serve'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/journey/router.rb:52:in `block in serve'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/journey/router.rb:35:in `each'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/journey/router.rb:35:in `serve'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/routing/route_set.rb:840:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/batch-loader-1.5.0/lib/batch_loader/middleware.rb:11:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/rack-attack-6.5.0/lib/rack/attack.rb:113:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/omniauth-1.9.1/lib/omniauth/builder.rb:45:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/decidim-core-0.24.2/app/middleware/decidim/strip_x_forwarded_host.rb:11:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/decidim-core-0.24.2/app/middleware/decidim/current_organization.rb:21:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/cookies.rb:670:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:98:in `run_callbacks'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/rack/logger.rb:38:in `call_app'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/rack/logger.rb:26:in `block in call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `block in tagged'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:28:in `tagged'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `tagged'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/rack/logger.rb:26:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/request_id.rb:27:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/redirector-1.1.7/lib/redirector/middleware.rb:25:in `response'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/redirector-1.1.7/lib/redirector/middleware.rb:10:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/executor.rb:14:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/prometheus_exporter-0.7.0/lib/prometheus_exporter/middleware.rb:34:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/engine.rb:524:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/puma-5.3.1/lib/puma/configuration.rb:249:in `call'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/puma-5.3.1/lib/puma/request.rb:76:in `block in handle_request'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/puma-5.3.1/lib/puma/thread_pool.rb:338:in `with_force_shutdown'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/puma-5.3.1/lib/puma/request.rb:75:in `handle_request'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/puma-5.3.1/lib/puma/server.rb:437:in `process_client'
[bde835d7-fb04-4c45-ab08-38687ad79ba1] bundle/ruby/2.7.0/gems/puma-5.3.1/lib/puma/thread_pool.rb:145:in `block in spawn_thread'
```

**Comment by carlobeltrame** [comment]
Dasselbe Problem wurde bei Zürich bereits von Thomas gefixt: https://github.com/puzzle/decidim-zuerich/commit/cd4c847ce9f1af3baa2612e466f57b59aa425d15
Bei Decidim wurde das auch schon gefixt, aber der Fix ist noch in keinem Release drin: https://github.com/decidim/decidim/pull/7854

Ich übernehme mal die offizielle Änderung von Decidim bei uns.

**Comment by innosmith** [comment]
@carlobeltrame : dann lass uns das bitte rasch auf INT testen und wenn erfolgreich, auf PROD releasen. @Naadjjaa zur Info.

**Comment by carlobeltrame** [comment]
@innosmith Fix ist auf INT.

**Comment by innosmith** [comment]
@carlobeltrame, @Naadjjaa  : nur mit Registrierung funktioniert es. Sobald ich ein Anmeldeformular zusätzlich hinzufüge, fühlt es zum Serverfehler siehe Screenshot. Fehlerzeitpunkt 28.09.2021 12:31, reproduziert nach Logout und Login 12.32.

![Screenshot 2021-09-28 at 12 31 55](https://user-images.githubusercontent.com/75796635/135071415-8cbd1c9d-aa15-4301-9383-6e8a20563d17.png)

**Comment by carlobeltrame** [comment]
Dieser neue Fehler ist bei uns im Fehler-Sammel-Tool Sentry aufgetaucht. Das wird beim Debuggen helfen. https://sentry.puzzle.ch/pitc/decidim-luzern/issues/42832/

**Comment by carlobeltrame** [comment]
Ich habe den Fehler gefunden und behoben, es wurde durch unseren Umfragen-Email-Versand verursacht. Ist auf Integration ausgerollt.
